export const AppStore = [
    {
        id: 0,
        appName: 'Quotes',
        component: 'quote',
        icon: 'format_quote',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Quote App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 1,
        appName: 'Memo',
        component: 'memo',
        icon: 'note',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Memo App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 2,
        appName: 'Calculator',
        component: 'calc',
        icon: 'dialpad',
        allowResize: true,
        allowMaximize: false,
        allowMinimize: true,
        allowClose: true,
        title: 'Calculator App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 370,
        width: 500,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 3,
        appName: 'Settings',
        component: 'settings',
        icon: 'settings',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Settings',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 4,
        appName: 'Clock',
        component: 'clock',
        icon: 'alarm',
        allowResize: true,
        allowMaximize: false,
        allowMinimize: true,
        allowClose: true,
        title: 'Clock App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 500,
        width: 500,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 5,
        appName: 'TodoList',
        component: 'todo',
        icon: 'assignment',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'TodoList App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 6,
        appName: 'Help',
        component: 'help',
        icon: 'help_outline',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Help App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 7,
        appName: 'Shopping',
        component: 'shopping',
        icon: 'shopping_cart',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Shopping App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 8,
        appName: 'Dictionary',
        component: 'dictionary',
        icon: 'translate',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Dictionary App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 9,
        appName: 'Music',
        component: 'music',
        icon: 'audiotrack',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Music App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 10,
        appName: 'Movies',
        component: 'movies',
        icon: 'movie',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Movies App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 11,
        appName: 'E-Mail',
        component: 'email',
        icon: 'email',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'E-Mail App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 12,
        appName: 'Paint',
        component: 'paint',
        icon: 'brush',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Paint App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 13,
        appName: 'Images',
        component: 'images',
        icon: 'photo_library',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Images App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 14,
        appName: 'Weather',
        component: 'weather',
        icon: 'cloud_queue',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Weather App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 15,
        appName: 'Voice Recorder',
        component: 'voiceRec',
        icon: 'mic',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Voice Recorder App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 16,
        appName: 'Games',
        component: 'games',
        icon: 'casino',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Games App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 17,
        appName: 'Chat',
        component: 'chat',
        icon: 'chat',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Chat App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 18,
        appName: 'Code Editor',
        component: 'editor',
        icon: 'code',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Code Editor App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    },
    {
        id: 19,
        appName: 'Web Hub',
        component: 'webhub',
        icon: '',
        allowResize: true,
        allowMaximize: true,
        allowMinimize: true,
        allowClose: true,
        title: 'Web Hub App',
        isFocused: true,
        isHidden: false,
        isMax: false,
        height: 650,
        width: 650,
        posX: 0,
        posY: 0,
        posZ: 0,
    }
] ;
